version: '3'
services:
  web:
    build: .
    command: "service nginx start; scripts/docker-wait-pgsql; python scripts/migrate.py; uwsgi --socket /var/tmp/nodewatcher.sock --wsgi-file /code/mainpage/wsgi.py"
    entrypoint: scripts/docker-run
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/code
    ports:
      - "80:80"
  db:
    build:
      context: docker/database/
      dockerfile: Dockerfile
    environment:
        POSTGRESQL_USER: wlansi_cms
        POSTGRESQL_PASS: mainpage
        POSTGRESQL_DB: wlansi
    expose:
      - 5432